# Generated by Django 5.2.13 on 2026-04-20 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                ("user_role", models.CharField(blank=True, max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("VIEW", "Consultation"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("LOGIN_FAILED", "Échec de connexion"),
                            ("MFA_VERIFY", "Vérification MFA"),
                            ("MFA_SETUP", "Configuration MFA"),
                            ("EXPORT", "Export"),
                            ("ANALYZE", "Analyse IA"),
                            ("REPORT_GENERATE", "Génération rapport"),
                            ("REPORT_SIGN", "Signature rapport"),
                            ("PERMISSION_DENIED", "Accès refusé"),
                            ("API_KEY", "Utilisation clé API"),
                        ],
                        max_length=30,
                    ),
                ),
                ("resource", models.CharField(max_length=200)),
                ("resource_id", models.CharField(blank=True, max_length=100)),
                ("method", models.CharField(blank=True, max_length=10)),
                ("path", models.CharField(blank=True, max_length=500)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log d'audit",
                "verbose_name_plural": "Logs d'audit",
                "db_table": "audit_logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "action", "timestamp"],
                        name="audit_logs_user_id_26273a_idx",
                    ),
                    models.Index(
                        fields=["resource", "timestamp"],
                        name="audit_logs_resourc_fdd6d6_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "timestamp"],
                        name="audit_logs_ip_addr_932507_idx",
                    ),
                    models.Index(
                        fields=["action", "timestamp"],
                        name="audit_logs_action_474804_idx",
                    ),
                ],
            },
        ),
    ]
