# Generated by Django 5.2.13 on 2026-04-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verification_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="email_verification_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("radiologist", "Radiologist"),
                    ("user", "User"),
                    ("admin", "Administrateur"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
