# Generated by Django 5.2.13 on 2026-04-20 23:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("radiography", "0002_alter_radiography_exam_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyseIA",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("model_version", models.CharField(max_length=50)),
                ("results", models.JSONField(default=dict)),
                ("heatmap_path", models.CharField(blank=True, max_length=512)),
                ("duration_ms", models.IntegerField()),
                ("global_confidence", models.FloatField(blank=True, null=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente de validation"),
                            ("validated", "Validé par radiologue"),
                            ("corrected", "Corrigé par radiologue"),
                            ("rejected", "Rejeté"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("validation_notes", models.TextField(blank=True)),
                (
                    "radiography",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyse",
                        to="radiography.radiography",
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses_validated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Analyse IA",
                "verbose_name_plural": "Analyses IA",
            },
        ),
        migrations.CreateModel(
            name="Pathology",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("icd10_code", models.CharField(blank=True, max_length=10)),
                ("confidence_score", models.FloatField()),
                ("is_critical", models.BooleanField(default=False)),
                ("localisation", models.JSONField(blank=True, default=dict)),
                ("is_validated", models.BooleanField(default=False)),
                ("corrected_name", models.CharField(blank=True, max_length=100)),
                ("correction_notes", models.TextField(blank=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathologies",
                        to="analysis.analyseia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pathologie",
                "verbose_name_plural": "Pathologies",
                "ordering": ["-confidence_score"],
            },
        ),
        migrations.AddIndex(
            model_name="analyseia",
            index=models.Index(
                fields=["radiography"], name="analysis_an_radiogr_f83535_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyseia",
            index=models.Index(
                fields=["validation_status"], name="analysis_an_validat_09f0b1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="analyseia",
            index=models.Index(
                fields=["created_at"], name="analysis_an_created_cd9309_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pathology",
            index=models.Index(
                fields=["analysis"], name="analysis_pa_analysi_d90ebe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pathology",
            index=models.Index(fields=["name"], name="analysis_pa_name_33cf87_idx"),
        ),
        migrations.AddIndex(
            model_name="pathology",
            index=models.Index(
                fields=["is_critical"], name="analysis_pa_is_crit_83cd6f_idx"
            ),
        ),
    ]
