# Generated by Django 5.2.13 on 2026-04-20 23:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
        ("radiography", "0002_alter_radiography_exam_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnalyseIA",
            new_name="IAAnalysis",
        ),
        migrations.RenameIndex(
            model_name="iaanalysis",
            new_name="analysis_ia_radiogr_bdecd0_idx",
            old_name="analysis_an_radiogr_f83535_idx",
        ),
        migrations.RenameIndex(
            model_name="iaanalysis",
            new_name="analysis_ia_validat_47c3ed_idx",
            old_name="analysis_an_validat_09f0b1_idx",
        ),
        migrations.RenameIndex(
            model_name="iaanalysis",
            new_name="analysis_ia_created_b4a773_idx",
            old_name="analysis_an_created_cd9309_idx",
        ),
    ]
