# Generated by Django 5.2.13 on 2026-04-21 00:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analysis", "0002_rename_analyseia_iaanalysis_and_more"),
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rapport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("conclusions", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                ("pdf_path", models.CharField(blank=True, max_length=512)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("pending_signature", "En attente de signature"),
                            ("signed", "Signé"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("signature_date", models.DateTimeField(blank=True, null=True)),
                ("digital_signature", models.TextField(blank=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="analysis.iaanalysis",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="patients.patient",
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_signed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "written_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports_written",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport",
                "verbose_name_plural": "Rapports",
                "indexes": [
                    models.Index(
                        fields=["patient"], name="reports_rap_patient_827984_idx"
                    ),
                    models.Index(
                        fields=["statut"], name="reports_rap_statut_c09acb_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="reports_rap_created_c30043_idx"
                    ),
                    models.Index(
                        fields=["written_by"], name="reports_rap_written_33844f_idx"
                    ),
                ],
            },
        ),
    ]
