# Generated by Django 5.2.13 on 2026-04-21 00:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0002_rename_analyseia_iaanalysis_and_more"),
        ("patients", "0001_initial"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Rapport",
            new_name="Report",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="reports_rep_patient_c642a7_idx",
            old_name="reports_rap_patient_827984_idx",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="reports_rep_statut_0f9451_idx",
            old_name="reports_rap_statut_c09acb_idx",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="reports_rep_created_a6aabf_idx",
            old_name="reports_rap_created_c30043_idx",
        ),
        migrations.RenameIndex(
            model_name="report",
            new_name="reports_rep_written_c0054d_idx",
            old_name="reports_rap_written_33844f_idx",
        ),
    ]
