# Generated by Django 5.2.13 on 2026-04-20 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Radiography",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "exam_type",
                    models.CharField(
                        choices=[
                            ("thorax", "Thorax"),
                            ("membre_superieur", "Membre supérieur"),
                            ("membre_inferieur", "Membre inférieur"),
                            ("rachis", "Rachis"),
                            ("bassin", "Bassin"),
                            ("crane", "Crâne"),
                            ("autre", "Autre"),
                        ],
                        default="thorax",
                        max_length=50,
                    ),
                ),
                (
                    "image_format",
                    models.CharField(
                        choices=[("DICOM", "DICOM"), ("JPEG", "JPEG"), ("PNG", "PNG")],
                        max_length=10,
                    ),
                ),
                ("image_path", models.CharField(max_length=512)),
                ("thumbnail_path", models.CharField(blank=True, max_length=512)),
                ("taken_at", models.DateTimeField()),
                ("quality_score", models.FloatField(blank=True, null=True)),
                ("dicom_metadata", models.JSONField(blank=True, default=dict)),
                ("is_analyzed", models.BooleanField(default=False)),
                (
                    "analysis_status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("processing", "En cours"),
                            ("completed", "Terminée"),
                            ("failed", "Échouée"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="radiographies",
                        to="patients.patient",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="radiographies_uploaded",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Radiographie",
                "verbose_name_plural": "Radiographies",
                "indexes": [
                    models.Index(
                        fields=["patient"], name="radiography_patient_57c64b_idx"
                    ),
                    models.Index(
                        fields=["taken_at"], name="radiography_taken_a_46632a_idx"
                    ),
                    models.Index(
                        fields=["analysis_status"],
                        name="radiography_analysi_8e5daa_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by"], name="radiography_uploade_f30479_idx"
                    ),
                ],
            },
        ),
    ]
