# Generated by Django 5.2.13 on 2026-04-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radiography", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="radiography",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("chest", "Chest"),
                    ("upper_limb", "Upper Limb"),
                    ("lower_limb", "Lower Limb"),
                    ("spine", "Spine"),
                    ("pelvis", "Pelvis"),
                    ("skull", "Skull"),
                    ("other", "Other"),
                    ("elbow", "Elbow"),
                    ("finger", "Finger"),
                    ("forearm", "Forearm"),
                    ("hand", "Hand"),
                    ("humerus", "Humerus"),
                    ("shoulder", "Shoulder"),
                    ("wrist", "Wrist"),
                    ("atelectasis", "Atelectasis"),
                    ("cardiomegaly", "Cardiomegaly"),
                    ("effusion", "Pleural Effusion"),
                    ("infiltration", "Infiltration"),
                    ("mass", "Mass"),
                    ("nodule", "Nodule"),
                    ("pneumonia", "Pneumonia"),
                    ("pneumothorax", "Pneumothorax"),
                    ("consolidation", "Consolidation"),
                    ("edema", "Edema"),
                    ("emphysema", "Emphysema"),
                    ("fibrosis", "Fibrosis"),
                    ("pleural_thickening", "Pleural Thickening"),
                    ("hernia", "Hernia"),
                ],
                default="thorax",
                max_length=50,
            ),
        ),
    ]
